### ISSUE TITLE
Maybe a bug: When users start leaving, the user list doesn't update, so the colors no longer alternate like intended

### ISSUE THREAD

**Issue by Nytra** [Banane9/NeosSessionUsersDetails#1]
I noticed this bug when using the previous mod called AlternatingSessionUserList, and I am just assuming that the same issue is here. Correct me if I'm wrong. Basically if users leave you can get for example two or more bars in a row of the same color.

**Comment by Banane9** [comment]
this has been fixed, yes... please don't report issues without verifying it still exists 😅
